config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, skip: [:session, :password, :registration], controllers: { omniauth_callbacks: "omniauth_callbacks" }
  devise_scope :user do
    get   '/users/auth/failure'   => 'omniauth_callbacks#failure'
    post  '/finish_registration'  => 'omniauth_callbacks#finish_registration'
    get   '/finish_registration'  => 'events#index'
  end
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users, skip: [:registrations, :omniauth_callbacks]
    devise_scope :user do
      resource :registration,
               only: [:new, :create, :edit, :update],
               path: 'users',
               path_names: { new: 'sign_up' },
               controller: 'devise/registrations',
               as: :user_registration do
        get :cancel
      end
    end

    resources :feedbacks do
      post 'like', to: 'socializations#like'
      delete 'unlike', to: 'socializations#unlike'
      resources :comments, module: :feedbacks
    end

    match 'notifications' => 'activities#notifications', :via => :get
    match 'notifications_count' => 'activities#notifications_count', :via => :get

    resources :activities, only: [:index]
    resources :languages
    resources :profiles do
      patch 'save_photo', to: 'profiles#save_photo'
      patch 'save_cover_img', to: 'profiles#save_cover_img'
    end

    resources :events do
      member do
        post 'members', to: 'events#members'
      end
      post 'like', to: 'socializations#like'
      delete 'unlike', to: 'socializations#unlike'
      resources :comments, module: :events
    end
    resources :event_memberships do
      collection do
        get 'as_tutor'
        get 'as_member'
        get 'show_event_members/:event_id' => 'event_memberships#show_event_members', as: :show_members
        post 'update_rate/:event_id/:rate_id' => 'event_memberships#update_rate', as: :update_rate
      end

      member do
        post 'member_attended' => 'event_memberships#member_attended', as: :member_attended
        post 'member_not_attended' => 'event_memberships#member_not_attended', as: :member_not_attended
        post 'rate_member' => 'event_memberships#rate_member', as: :rate
      end
    end
    post 'event_memberships/join/:event_id' => 'event_memberships#join', as:   :join_event
    delete 'event_memberships/leave/:event_id' => 'event_memberships#leave', as: :leave_event
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'events#index'
  end
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :events, dependent: :destroy
  has_many :rated_memberships, dependent: :destroy
  has_many :language_sessions_counters, dependent: :destroy
  validates_presence_of :description
  has_attached_file :flag_image, styles: { micro: '30x20#', small: '60x40#', medium: '120x80#', original: '240x160#' }
  validates_attachment :flag_image, content_type: { content_type: ['image/jpeg', 'image/png'] }
  validates_with AttachmentSizeValidator, attributes: :flag_image, less_than: 1.megabytes
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_language, only: [:show, :edit, :update, :destroy]
  include Profiled

  authorize_resource

  def index
    @languages = Language.all
  end

  def show
  end

  def new
    @language = Language.new
  end

  def edit
  end

  def create
    @language = Language.new(language_params)

    respond_to do |format|
      if @language.save
        format.html { redirect_to @language, notice: 'Language was successfully created.' }
        format.json { render :show, status: :created, location: @language }
      else
        format.html { render :new }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /languages/1
  # PATCH/PUT /languages/1.json
  def update
    respond_to do |format|
      if @language.update(language_params)
        format.html { redirect_to @language, notice: 'Language was successfully updated.' }
        format.json { render :show, status: :ok, location: @language }
      else
        format.html { render :edit }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /languages/1
  # DELETE /languages/1.json
  def destroy
    @language.destroy
    respond_to do |format|
      format.html { redirect_to languages_url, notice: 'Language was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_language
      @language = Language.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def language_params
      params.require(:language).permit(:description, :flag_image)
    end
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/views/languages/_form.html.erb
<%= form_for(language, html: { multipart: true }) do |f| %>
  <div class="box-body">

    <% if language.errors.any? %>
        <%= render 'shared/errors', object: language %>
    <% end %>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :flag_image %>
      <%= f.file_field :flag_image %>
    </div>
  </div>

  <div class="box-footer">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/languages/edit.html.erb
<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title">Editing Language</h3>
  </div>
  <%= render 'form', language: @language %>
  <div class="box-footer">
    <%= link_to 'Show', @language %> |
    <%= link_to 'Back', languages_path %>
  </div>
</div>

app/views/languages/index.html.erb
<div class="box">
  <div class="box-header with-border">
    <h3 class="box-title">Add new language</h3>
    <div class="box-tools pull-right">
      <%= link_to 'New Language', new_language_path, class: 'btn btn-sm btn-primary' %>
    </div>
  </div>
</div>

<div class="row">

    <% @languages.each do |language| %>

      <div class="col-md-6">
        <div class="box box-info">
          <div class="box-header with-border">
            <h3 class="box-title">Language</h3>
          </div>
          <div class="box-body">
            <dl class="dl-horizontal">
              <dt>Description:</dt>
              <dd><%= language.description %></dd>

              <dt>Events total:</dt>
              <dd><%= language.events_count %></dd>

              <dt>Micro image:</dt>
              <dd><%= image_tag(language.flag_image.url(:micro)) if language.flag_image? %></dd>

              <dt>Small:</dt>
              <dd><%= image_tag(language.flag_image.url(:small)) if language.flag_image? %></dd>


              <dt>Medium:</dt>
              <dd><%= image_tag(language.flag_image.url(:medium)) if language.flag_image? %></dd>


              <dt>Original:</dt>
              <dd><%= image_tag(language.flag_image.url(:original)) if language.flag_image? %></dd>

            </dl>
          </div>
          <div class="box-footer">
            <%= language.description %> |
            <%= link_to 'Show', language %> |
            <%= link_to 'Edit', edit_language_path(language) %> |
            <%= link_to 'Destroy', language, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
      </div>

    <% end %>
</div>

<br>

app/views/languages/new.html.erb
<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title">New Language</h3>
  </div>
  <%= render 'form', language: @language %>
  <div class="box-footer">
    <%= link_to 'Back', languages_path %>
  </div>
</div>

app/views/languages/show.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="box box-info">
      <div class="box-header with-border">
        <h3 class="box-title">Language</h3>
      </div>
      <div class="box-body">
        <dl class="dl-horizontal">
          <dt>Description:</dt>
            <dd><%= @language.description %></dd>

          <dt>Micro image:</dt>
            <dd><%= image_tag(@language.flag_image.url(:micro)) if @language.flag_image? %></dd>

          <dt>Small:</dt>
            <dd><%= image_tag(@language.flag_image.url(:small)) if @language.flag_image? %></dd>


          <dt>Medium:</dt>
            <dd><%= image_tag(@language.flag_image.url(:medium)) if @language.flag_image? %></dd>


          <dt>Original:</dt>
            <dd><%= image_tag(@language.flag_image.url(:original)) if @language.flag_image? %></dd>

        </dl>
      </div>
      <div class="box-footer">
        <%= link_to t('edit'), edit_language_path(@language) %> |
        <%= link_to t('back'), languages_path %>
      </div>
    </div>
  </div>
</div>