config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, skip: [:session, :password, :registration], controllers: { omniauth_callbacks: "omniauth_callbacks" }
  devise_scope :user do
    get   '/users/auth/failure'   => 'omniauth_callbacks#failure'
    post  '/finish_registration'  => 'omniauth_callbacks#finish_registration'
    get   '/finish_registration'  => 'events#index'
  end
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users, skip: [:registrations, :omniauth_callbacks]
    devise_scope :user do
      resource :registration,
               only: [:new, :create, :edit, :update],
               path: 'users',
               path_names: { new: 'sign_up' },
               controller: 'devise/registrations',
               as: :user_registration do
        get :cancel
      end
    end

    resources :feedbacks do
      post 'like', to: 'socializations#like'
      delete 'unlike', to: 'socializations#unlike'
      resources :comments, module: :feedbacks
    end

    match 'notifications' => 'activities#notifications', :via => :get
    match 'notifications_count' => 'activities#notifications_count', :via => :get

    resources :activities, only: [:index]
    resources :languages
    resources :profiles do
      patch 'save_photo', to: 'profiles#save_photo'
      patch 'save_cover_img', to: 'profiles#save_cover_img'
    end

    resources :events do
      member do
        post 'members', to: 'events#members'
      end
      post 'like', to: 'socializations#like'
      delete 'unlike', to: 'socializations#unlike'
      resources :comments, module: :events
    end
    resources :event_memberships do
      collection do
        get 'as_tutor'
        get 'as_member'
        get 'show_event_members/:event_id' => 'event_memberships#show_event_members', as: :show_members
        post 'update_rate/:event_id/:rate_id' => 'event_memberships#update_rate', as: :update_rate
      end

      member do
        post 'member_attended' => 'event_memberships#member_attended', as: :member_attended
        post 'member_not_attended' => 'event_memberships#member_not_attended', as: :member_not_attended
        post 'rate_member' => 'event_memberships#rate_member', as: :rate
      end
    end
    post 'event_memberships/join/:event_id' => 'event_memberships#join', as:   :join_event
    delete 'event_memberships/leave/:event_id' => 'event_memberships#leave', as: :leave_event
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'events#index'
  end
end

app/models/event.rb
class Event < ApplicationRecord
  include PublicActivity::Common

  belongs_to :user, counter_cache: true, touch: true
  belongs_to :language, counter_cache: true, touch: true
  has_many :memberships,  class_name: 'EventMembership', dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :activities, as: :trackable, class_name: 'PublicActivity::Activity', dependent: :destroy

  has_attached_file :event_bg_image,
                    styles: { original: '550x150#' },
                    default_url: ':event_bg_image'

  validates_attachment :event_bg_image, content_type: { content_type: ['image/jpeg', 'image/png'] }
  validates_with AttachmentSizeValidator, attributes: :event_bg_image, less_than: 1.megabytes

  validates_presence_of :max_members, :language
  validates_datetime :ends_at, :starts_at, after: DateTime.current + 24.hours
  validates_datetime :ends_at, after: :starts_at
  # events should be no more than one month ahead
  # validates_datetime :ends_at, before: DateTime.current + 1.month
  validates_numericality_of :latitude, :longitude
  validates_inclusion_of :cefrl, in: %w( A1 A2 B1 B2 C1 C2 ) # Common European Framework of Reference for Languages
  validates :title, length: { in: 4..140 }
  validates :description, length: { in: 10..3000 }
  validates :address, length: { in: 10..255 }

  acts_as_likeable
  acts_as_followable

  def joinable?(membership)
    return false if user == membership.user
    return false if starts_at < Time.zone.now
    return true
  end

end

app/controllers/events/comments_controller.rb
class Events::CommentsController < CommentsController
  before_action :set_commentable

  private

  def set_commentable
    @commentable = Event.find(params[:event_id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :edit, :update, :destroy]
  before_action :set_event, only: [:edit, :update, :destroy, :members]
  before_action :set_count_events, only: [:index]
  before_action :get_events, only: [:index]
  before_action :set_count_memberships, only: [:index]
  before_action :set_page_title

  include Profiled
  include Breadcrumbed
  before_action :set_event_index_breadcrumb, only: [:index, :show, :edit, :new]

  authorize_resource

  def index
    @languages = Language.all.order(events_count: 'desc')
  end

  def show
    @event = Event.where(id: params[:id]).includes(:language, user: [:profile], comments: [user: [:profile]]).first
    add_breadcrumb I18n.t('breadcrumbs.events.show'), event_path(@event)
    build_markers_hash
  end

  # GET /events/new
  def new
    add_breadcrumb I18n.t('breadcrumbs.events.new'), new_event_path
    @event = Event.new
    build_markers_hash
  end

  # GET /events/1/edit
  def edit
    authorize! :update, @event
    build_markers_hash
    add_breadcrumb I18n.t('breadcrumbs.events.edit'), edit_event_path
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.build(event_params)
    build_markers_hash
    respond_to do |format|
      if @event.save
        @event.create_activity key: 'event.create', owner: current_user
        current_user.follow!(@event)
        format.html { redirect_to @event, flash: { success: I18n.t('events.event_was_successfully_created') }}
      else
        add_breadcrumb I18n.t('breadcrumbs.events.new'), new_event_path
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        @event.create_activity key: 'event.update', owner: current_user
        format.html { redirect_to @event, flash: { success: I18n.t('events.event_was_successfully_updated') }}
      else
        format.html { render :edit }
      end
    end
  end

  def members
    @members = EventMembership.where(event_id: params[:id]).includes(:profile)
    respond_to do |format|
      format.json { render 'members.json.jbuilder', status: :ok, layout: false }
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    Follow.remove_followers(@event)

    respond_to do |format|
      format.html { redirect_to events_url, flash: { success: I18n.t('events.event_was_successfully_destroyed') }}
      format.json { head :no_content }
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def set_page_title
    @page_title = I18n.t('page_titles.events')
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:title, :description, :address, :starts_at, :ends_at, :language_id, :max_members, :latitude, :longitude, :cefrl, :event_bg_image)
  end

  def set_count_events
    @count_events = Event.all.size
  end

  def get_events
    @events = Event.where('starts_at >= ?', Time.zone.now).order(starts_at: :asc).includes(:language, user: [:profile], comments: [:user] ).page(params[:page]).per(10)
  end

  def set_count_memberships
    @count_memberships = EventMembership.all.size
  end

  def set_event_index_breadcrumb
    add_breadcrumb I18n.t('breadcrumbs.events.index'), events_path
  end

  def build_markers_hash
    @hash = Gmaps4rails.build_markers(@event) do |event, marker|
      marker.lat event.latitude ||= Rails.application.secrets.default_latitude
      marker.lng event.longitude ||= Rails.application.secrets.default_longitude
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div class="box box-widget collapsed-box event_box" id="event_<%= event.id %>">
  <div class="box-header with-border">
    <div class="widget-user" >
      <% if event.event_bg_image? %>
        <div class="widget-user-header" style="background: url('<%= event.event_bg_image.url %>') center center no-repeat; background-size: cover;"></div>
    <% else %>
        <div class="widget-user-header"></div>
    <% end %>
      <div class="widget-user-image">
        <%= show_profile_img(event.user, 'small', 'img-circle') %>
      </div>
    </div>

  <%= render partial: 'events/event_box_header', locals: { event: event } %>
    <button type="button" class="btn btn-sm btn-block event_description" data-widget="collapse" style="background: none;"><%= t('event_memberships.event_description') %> <i class="fa fa-plus"></i>
    </button>
  </div>

  <div class="box-body">
    <%= render partial: 'events/event_box_body', locals: { event: event } %>
  </div>

  <div class="box-footer event-btns">
    <%= render partial: 'events/event_box_footer', locals: { event: event } %>
  </div>

  <%= render partial: 'comments/comments', locals: { commentable: event } %>

  <div class="overlay hidden">
    <i class="fa fa-refresh fa-spin"></i>
  </div>
</div>

app/views/events/_event_box_body.html.erb
<%= markdown(event.description) %>
<p><strong><%= t'events.event.address' %>: </strong> <%= event.address %></p>
<div class="no-padding">
  <ul class="members-list members_list_<%= event.id %> clearfix">
  </ul>
</div>

app/views/events/_event_box_footer.html.erb
<% if user_signed_in? %>
  <span id="event_like_btn_<%= event.id %>" class="like-btn">
    <%= render partial: 'events/like_btn', locals: {event: event} %>
  </span>
  <span class="event_join_btn_<%= event.id %>">
    <% if current_user.member_of?(event) %>
      <%= link_to leave_event_path(event), class: 'event_participation_btn btn btn-danger btn-flat', method: :delete, remote: true, data: { type: :json, confirm: t('are_you_sure') } do %>
          <i class="fa fa-user-times"></i> <%= t'events.leave' %>
      <% end %>
    <% else %>
      <%= link_to join_event_path(event), class: 'event_participation_btn btn btn-default btn-flat', method: :post, remote: true, data: { type: :json } do %>
          <i class="fa fa-user-plus"></i> <%= t'events.join' %>
      <% end %>
    <% end %>
  </span>
<% end %>

<%= link_to members_event_path(event),
            class: 'load_members load_members_#{event.id} btn btn-default btn-flat',
            remote: true,
            method: :post,
            data: {
                event_id: event.id,
                type: :json
            } do %>
    <i class="fa fa-users"></i> <%= t'events.show_members' %>
<% end %>

<%= link_to_unless_current("<i class='fa fa-map-marker'></i> #{t('events.show_on_map')}".html_safe, event_path(event), class: 'btn btn-default btn-flat') do

end%>
<% if user_signed_in? && can?(:crud, event) %>
  <span class="pull-right text-muted">
    <%= link_to t('show'), event, class: 'btn btn-xs btn-default btn-flat' %> |
    <%= link_to t('edit'), edit_event_path(event), class: 'btn btn-xs btn-warning btn-flat' %> |
    <%= link_to t('destroy'), event, method: :delete, class: 'btn btn-xs btn-danger btn-flat', data: { confirm: t('are_you_sure')} %>
  </span>
<% end %>

app/views/events/_event_box_header.html.erb
<div class="user-block">
  <span>
        <%= image_tag(event.language.flag_image.url(:micro), class: 'flag-micro') if  event.language.flag_image? %>
        &nbsp
        <%= link_to profile_path(event.user.profile) do %>
          <%= event.user.profile.firstname %> <%= event.user.profile.lastname %></a>
        <% end %>
      </span>
  <span class="description"><%= event.likers_count %> Likes</span>
  <span class="description"> </span>
  <div class="clearfix"></div>
  <ul class="list-group">
    <li class="list-group-item">
      <span class="label label-default wday_<%= event.starts_at.wday %>"><%= I18n.l event.starts_at, format: '%a' %></span>
      <%= I18n.l event.starts_at, format: ("%d %b") %>,
      <%= t ('events.event.starts_at') %>
      <%= I18n.l event.starts_at, format: ("%H:%M") %>
    </li>
    <li class="list-group-item"><h4><%= event.title %></h4></li>
    <li class="list-group-item"><i class="fa fa-language" data-original-title='<%= t 'events.event.language' %>' data-toggle="tooltip" ></i>  <%= event.language.description %>  |  <i class="fa fa-line-chart" data-original-title='<%= t 'activerecord.attributes.event.cefrl' %>' data-toggle="tooltip" ></i> <%= t("events.event.cefrl_options.#{event.cefrl}")%>  |  <i class="fa fa-users" data-original-title='<%= t 'events.event.max_members' %>' data-toggle="tooltip" ></i>  <%= event.event_memberships_count %> / <%= event.max_members %> | <i class="fa fa-comments" data-original-title='<%= t 'events.event.comments' %>' data-toggle="tooltip" ></i>  <%= (t("comments",count: event.comments_count)).capitalize %></li>
  </ul>
</div>

app/views/events/_form.html.erb
<%= form_for(event, html: { multipart: true }) do |f| %>
  <% if event.errors.any? %>
    <%= render 'shared/errors', object: event %>
  <% end %>

  <div class="row">
    <div class="field form-group col-sm-12 col-md-6">
      <%= f.label :language %>
      <%= f.select(:language_id, options_for_select(Language.all.order(events_count: 'desc' ).map {|p| [p.description, p.id, {'data-image' => p.flag_image.url(:micro)}]}), {}, { class: 'form-control' }) %>
    </div>

    <div class="field form-group col-sm-12 col-md-6">
      <%= f.label :cefrl %>
      <%= f.select(:cefrl, options_for_select(
            [
              [I18n.t('events.event.cefrl_options.A1'),'A1'],
              [I18n.t('events.event.cefrl_options.A2'),'A2'],
              [I18n.t('events.event.cefrl_options.B1'),'B1'],
              [I18n.t('events.event.cefrl_options.B2'),'B2'],
              [I18n.t('events.event.cefrl_options.C1'),'C1'],
              [I18n.t('events.event.cefrl_options.C2'),'C2']
            ],
            [event.cefrl]
          ), {include_blank: false}, {class: "form-control"})
      %>
    </div>
  </div>



  <div class="field form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :event_bg_image %>
    <%= f.file_field :event_bg_image %>
  </div>

  <div class="field form-group">
    <%= f.label :description %>
    <%= md_simple_editor  do %>
      <%= f.text_area :description, class: 'form-control' %>
    <% end %>
  </div>

  <div class="field form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div class="row">
    <div class="field form-group col-sm-12 col-md-4">
      <%= f.label :starts_at %>
      <%= f.text_field :starts_at, class: 'form-control', id: 'datetimepicker1' %>
    </div>

    <div class="field form-group col-sm-12 col-md-4">
      <%= f.label :ends_at %>
      <%= f.text_field :ends_at, class: 'form-control', id: 'datetimepicker2' %>
    </div>

    <%= f.hidden_field :latitude, id: 'gmap_latitude' %>
    <%= f.hidden_field :longitude, id: 'gmap_longitude' %>
    <%= f.hidden_field :gmap_zoom, id: 'gmap_zoom' %>

    <div class="field form-group col-sm-12 col-md-4">
      <%= f.label :max_members %>
      <%= f.number_field :max_members, class: 'form-control' %>
    </div>
  </div>

  <div class="field form-group ">
    <small class="help-block"><%= t('events.click_on_map_to_choose_place') %></small>
    <div id="map" style='width: 920px; height: 400px;' class="img-responsive"></div>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

<script src="//maps.google.com/maps/api/js?key=<%= Rails.application.secrets.google_map_api_key %>"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
<script type="application/javascript">
// flags in select
  $(document).ready(function(e) {
    try {
      $("body select#event_language_id").msDropDown();
    } catch(e) {
      alert(e.message);
    }
  });
//  /flags in select

  handler = Gmaps.build('Google');
  var markers_options = { draggable: true };
  handler.buildMap({
        provider: { auto_zoom: false },
        internal: {id: 'map'}},
      function(){
        markers = handler.addMarkers(<%= raw @hash.to_json %>, markers_options);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        handler.getMap().setZoom(16);

        // Callback function
        _.each(markers, listenToDragDrop)

        // On click, clear markers, place a new one, update coordinates in the form
        google.maps.event.addListener(handler.getMap(), 'click', function(event) {
          clearOverlays();
          placeMarker(event.latLng);
          updateFormLocation(event.latLng);
        });
      });

  function listenToDragDrop(marker){
    google.maps.event.addListener(marker.getServiceObject(), 'dragend', function() {
      updateFormLocation(marker.getServiceObject().getPosition());
    });
  }

  // Other functions
  // Update form attributes with given coordinates
  function updateFormLocation(latLng) {
    $('#gmap_latitude').val(latLng.lat());
    $('#gmap_longitude').val(latLng.lng());
    $('#gmap_zoom').val(handler.getMap().getZoom());
  }

  // Add a marker with an open infowindow
  function placeMarker(latLng) {
    var marker = handler.addMarker({
      lat: latLng.lat(),
      lng: latLng.lng(),
      infowindow: '<div class="popup"><%= t('events.drag_me_and_adjust_the_zoom_level') %></p>'
    }, markers_options)

    markers.push(marker)

    // Set and open infowindow
    google.maps.event.trigger(marker.getServiceObject(), 'click');

    listenToDragDrop(marker);
  }

  // // Removes the overlays from the map, including the ones loaded with the map itself
  function clearOverlays() {
    handler.removeMarkers(markers);
    markers = [];
  }
</script>

app/views/events/_info_boxes.html.erb
<div class="row">
  <div class="col-xs-6 col-md-6">
    <div class="small-box bg-aqua">
      <div class="inner">
        <h3><%= @count_events %></h3>
        <p>
          <%= t("events.active_events",count: @count_events) %>
          <abbr title="<%= t'the_counter_is_not_updated_immediately' %>">*</abbr>
        </p>
      </div>
      <div class="icon">
        <i class="fa fa-comments-o"></i>
      </div>
    </div>
  </div>

  <div class="col-xs-6 col-md-6">
    <div class="small-box bg-yellow">
      <div class="inner">
        <h3><%= @count_memberships %></h3>
        <p>
          <%= t("events.joined_members",count: @count_memberships) %>
          <abbr title="<%= t'the_counter_is_not_updated_immediately' %>">*</abbr>
        </p>
      </div>
      <div class="icon">
        <i class="fa fa-users"></i>
      </div>
    </div>
  </div>
</div>

app/views/events/_like_btn.html.erb
<% if event.liked_by?(current_user) %>
    <%= link_to event_unlike_path(event), method: :delete, remote: true, class: "btn btn-primary btn-flat" do %>
        <i class="fa fa-thumbs-o-up"></i> <%= event.likers_count %> Like
    <% end %>
<% else %>
    <%= link_to event_like_path(event), method: :post, remote: true, class: "btn btn-default btn-flat" do %>
        <i class="fa fa-thumbs-o-up"></i>  <%= event.likers_count if event.likers_count!=0 %> Like
    <% end %>
<% end %>

app/views/events/_show_gmap.html.erb
<script src="//maps.google.com/maps/api/js?key=<%= Rails.application.secrets.google_map_api_key %>"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

<div class="box box-widget">
  <div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Google Maps</h3>
    </div>
    <div class="box-body">
      <div id="map-<%= event.id %>" style='width: 920px; height: 400px;' class="img-responsive"></div>
    </div>
  </div>
</div>

<script type="application/javascript">
  handler = Gmaps.build('Google');
  var markers_options = { draggable: false };
  handler.buildMap({
        provider: { auto_zoom: false },
        internal: {id: 'map-<%= event.id %>'}},
      function(){
        markers = handler.addMarkers(<%= raw coordinates.to_json %>, markers_options);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        handler.getMap().setZoom(16);
      });
</script>

app/views/events/edit.html.erb
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- okgo create new event -->
<ins class="adsbygoogle"
     style="display:block;margin-bottom:20px;"
     data-ad-client="ca-pub-5677662134676433"
     data-ad-slot="7448703599"
     data-ad-format="auto"></ins>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({});
</script>
<div class="clearfix"></div>

<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title">Edit Event</h3>
  </div>
  <div class="box-body">
    <%= render 'form', event: @event %>
  </div>

  <div class="box-footer">
    <%= link_to t('show'), @event, class: 'btn btn-default'  %> |
    <%= link_to t('back'), events_path, class: 'btn btn-default' %>
  </div>
</div>

app/views/events/index.html.erb
<%= render 'events/info_boxes' %>
<div class="box box-widget">
  <div class="box-header hidden-xs with-border">
    <% @languages.each do |lang| %>
      <% if lang.events_count > 0 %>
            <div class="btn-group-vertical flag-with-count">
              <button type="button" class="btn btn-default btn-flat"><%= image_tag(lang.flag_image.url(:micro), class: 'flag-micro') if  lang.flag_image? %></button>
              <button type="button" class="btn btn-default btn-flat"><%= lang.events_count %></button>
            </div>
      <% end %>
    <% end %>
    <div class="box-tools pull-right">
      <%= link_to t('events.create_new_event'), new_event_path, class: 'btn-block btn bg-maroon btn-flat', style: 'padding: 24px 33px; font-weight: bolder; font-size: 15px; line-height: 0;' %>
    </div>
  </div>
  <div class="box-header visible-xs with-border">
    <%= link_to t('events.create_new_event'), new_event_path, class: 'btn btn-block bg-maroon btn-flat', style: 'padding: 24px 33px; font-weight: bolder; font-size: 15px; line-height: 0;' %>
  </div>
  <div class="box-footer visible-xs">
    <% @languages.each do |lang| %>
        <% if lang.events_count > 0 %>
            <div class="btn-group-vertical flag-with-count">
              <button type="button" class="btn btn-default btn-flat"><%= image_tag(lang.flag_image.url(:micro), class: 'flag-micro') if  lang.flag_image? %></button>
              <button type="button" class="btn btn-default btn-flat"><%= lang.events_count %></button>
            </div>
        <% end %>
    <% end %>
  </div>
</div>

  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <!-- okgo before events -->
  <ins class="adsbygoogle"
       style="display:block;margin-bottom:20px;"
       data-ad-client="ca-pub-5677662134676433"
       data-ad-slot="3129581995"
       data-ad-format="auto"></ins>
  <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
  </script>

<div class="row">
    <% @events.each_slice(2) do |events| %>
      <% events.each do |event| %>
        <div class="col-xs-12 col-md-6 event-resizing-div">
          <%= render partial: 'events/event', locals: {event: event}%>
        </div>
      <% end %>
        <div class="clearfix"></div>
    <% end %>
</div>

<%= paginate @events, window: 2 %>
<%= render partial: 'handlebars/members_template' %>


<script type="text/javascript" charset="utf-8">
  $('.event_description').on('click', function(){
    var eventWrapper = $(this).closest('.event-resizing-div');
    eventWrapper.toggleClass('col-md-6', 'col-md-12');
  });
</script>

app/views/events/new.html.erb
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- okgo create new event -->
<ins class="adsbygoogle"
     style="display:block;margin-bottom:20px;"
     data-ad-client="ca-pub-5677662134676433"
     data-ad-slot="7448703599"
     data-ad-format="auto"></ins>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({});
</script>
<div class="clearfix"></div>

<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title"><%= t('events.event.new_event') %></h3>
  </div>
  <div class="box-body">
    <%= render 'form', event: @event %>
  </div>
  <div class="box-footer">
    <%= link_to 'Back', events_path, class: 'btn btn-default pull-right' %>
  </div>
</div>

app/views/events/show.html.erb
<%= render partial: 'events/event', locals: {event: @event}%>

<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- okgo on event page -->
<ins class="adsbygoogle"
     style="display:block;margin-bottom:15px;"
     data-ad-client="ca-pub-5677662134676433"
     data-ad-slot="4466714395"
     data-ad-format="auto"></ins>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({});
</script>
<div class="clearfix"></div>

<%= render partial: 'events/show_gmap', locals: {event: @event, coordinates: @hash }%>
<%= render partial: 'handlebars/event_like_btn_template' %>
<%= render partial: 'handlebars/members_template' %>