config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, skip: [:session, :password, :registration], controllers: { omniauth_callbacks: "omniauth_callbacks" }
  devise_scope :user do
    get   '/users/auth/failure'   => 'omniauth_callbacks#failure'
    post  '/finish_registration'  => 'omniauth_callbacks#finish_registration'
    get   '/finish_registration'  => 'events#index'
  end
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users, skip: [:registrations, :omniauth_callbacks]
    devise_scope :user do
      resource :registration,
               only: [:new, :create, :edit, :update],
               path: 'users',
               path_names: { new: 'sign_up' },
               controller: 'devise/registrations',
               as: :user_registration do
        get :cancel
      end
    end

    resources :feedbacks do
      post 'like', to: 'socializations#like'
      delete 'unlike', to: 'socializations#unlike'
      resources :comments, module: :feedbacks
    end

    match 'notifications' => 'activities#notifications', :via => :get
    match 'notifications_count' => 'activities#notifications_count', :via => :get

    resources :activities, only: [:index]
    resources :languages
    resources :profiles do
      patch 'save_photo', to: 'profiles#save_photo'
      patch 'save_cover_img', to: 'profiles#save_cover_img'
    end

    resources :events do
      member do
        post 'members', to: 'events#members'
      end
      post 'like', to: 'socializations#like'
      delete 'unlike', to: 'socializations#unlike'
      resources :comments, module: :events
    end
    resources :event_memberships do
      collection do
        get 'as_tutor'
        get 'as_member'
        get 'show_event_members/:event_id' => 'event_memberships#show_event_members', as: :show_members
        post 'update_rate/:event_id/:rate_id' => 'event_memberships#update_rate', as: :update_rate
      end

      member do
        post 'member_attended' => 'event_memberships#member_attended', as: :member_attended
        post 'member_not_attended' => 'event_memberships#member_not_attended', as: :member_not_attended
        post 'rate_member' => 'event_memberships#rate_member', as: :rate
      end
    end
    post 'event_memberships/join/:event_id' => 'event_memberships#join', as:   :join_event
    delete 'event_memberships/leave/:event_id' => 'event_memberships#leave', as: :leave_event
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'events#index'
  end
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  include PublicActivity::Common

  belongs_to :user, touch: true
  has_many :comments, as: :commentable, dependent: :destroy

  acts_as_likeable
  acts_as_followable

  validates_presence_of :user, :status
  validates_inclusion_of :status, :in => %w( positive negative suggestion )
  validates :feedback, length: { in: 7..2000 }
end

app/controllers/feedbacks/comments_controller.rb
class Feedbacks::CommentsController < CommentsController
  before_action :set_commentable

  private

  def set_commentable
    @commentable = Feedback.find(params[:feedback_id])
  end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :authenticate_user!, only: [:create, :edit, :update, :destroy]
  authorize_resource

  include Profiled
  include Breadcrumbed
  include Notified


  before_action :set_feedback_index_breadcrumb
  before_action :set_feedback, only: [:show, :edit, :update, :destroy]
  before_action :set_page_title

  # GET /feedbacks
  # GET /feedbacks.json
  def index
    @feedbacks = Feedback.order(created_at: 'desc').includes(:comments, user: [:profile]).page(params[:page]).per(20)
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
  end

  # GET /feedbacks/new
  def new
    @feedback = Feedback.new
  end

  # GET /feedbacks/1/edit
  def edit
    add_breadcrumb I18n.t('breadcrumbs.feedbacks.edit_feedback'), event_path(@feedback)
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @feedback = current_user.feedbacks.build(feedback_params)

    respond_to do |format|
      if @feedback.save
        current_user.follow!(@feedback)
        format.html { redirect_to @feedback, flash: { success: I18n.t('feedbacks.feedback_was_successfully_created') }}
        format.json { render :show, status: :created, location: @feedback }
      else
        format.html { render :new }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feedbacks/1
  # PATCH/PUT /feedbacks/1.json
  def update
    respond_to do |format|
      if @feedback.update(feedback_params)
        current_user.follow!(@feedback)
        format.html { redirect_to @feedback, flash: { success: I18n.t('feedbacks.feedback_was_successfully_updated') }}
        format.json { render :show, status: :ok, location: @feedback }
      else
        add_breadcrumb I18n.t('breadcrumbs.feedbacks.edit_feedback'), event_path(@feedback)
        format.html { render :edit }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback.destroy
    Follow.remove_followers(@feedback)
    respond_to do |format|
      format.html { redirect_to feedbacks_url, flash: { success: I18n.t('feedbacks.feedback_was_successfully_destroyed') }}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feedback_params
      params.require(:feedback).permit(:feedback, :status)
    end

    def set_feedback_index_breadcrumb
      add_breadcrumb I18n.t('breadcrumbs.feedback.index'), feedbacks_path
    end

    def set_page_title
      @page_title = I18n.t('page_titles.feedbacks')
    end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper


  def feedback_status(status)
    i_con = 'fa-heart bg-maroon' if status == "positive"
    i_con = 'fa-exclamation bg-yellow' if status == "negative"
    i_con = 'fa-lightbulb-o bg-aqua' if status == "suggestion"

    return "<i class='fa #{i_con}' title='#{status.to_s.capitalize}'></i>"
  end
end

app/views/feedbacks/_feedback.html.erb
<div id="feedback_<%= feedback.id %>" class="box box-widget feedback-box">
  <div class="box-header with-border">
    <div class="user-block">
      <%= link_to profile_path(feedback.user.profile) do %>
          <%= show_profile_img(feedback.user, :medium) %>
      <% end %>
      <span class="username"><a href="<%= profile_path(feedback.user.profile) %>"><%= feedback.user.profile.firstname %> <%=feedback.user.profile.lastname %></a></span>
      <span class="description"><%= time_ago_in_words(feedback.created_at) %> | <%= t("comments",count: feedback.comments_count) %> | <%= feedback.likers_count %> likes</span>
    </div>
    <div class="box-tools">
      <% if can?(:crud, feedback) %>
        <div class="btn-group hidden-xs">
          <%= link_to edit_feedback_path(feedback), class:'btn btn-xs btn-warning' do %>
            <i class="fa fa-pencil-square-o"></i> <%= t('edit') %>
          <% end %>
          <%= link_to feedback, method: :delete, class:'btn btn-xs btn-danger', data: { confirm: 'Are you sure?' } do %>
            <i class="fa fa-trash"></i> <%= t('destroy') %>
          <% end %>
        </div>
        <div class="btn-group hidden-sm hidden-md hidden-lg">
          <%= link_to edit_feedback_path(feedback), class:'btn btn-sm btn-warning' do %>
            <i class="fa fa-pencil-square-o"></i>
          <% end %>
          <%= link_to feedback, method: :delete, class:'btn btn-sm btn-danger', data: { confirm: 'Are you sure?' } do %>
            <i class="fa fa-trash"></i>
          <% end %>
        </div>
      <% end %>
      <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
      </button>
      <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
    </div>
  </div>
  <div class="box-body">
    <p>
      <%= markdown(feedback.feedback) %>
    </p>
  </div>
  <% if user_signed_in?  %>
    <div class="box-footer feedback-btns">
      <span id="feedback_like_btn_<%= feedback.id %>" class="like-btn">
        <%= render partial: 'feedbacks/like_btn', locals: { feedback: feedback } %>
      </span>
    </div>
  <% end %>

  <%= render partial: 'comments/comments', locals: { commentable: feedback } %>

  <div class="overlay hidden">
    <i class="fa fa-refresh fa-spin"></i>
  </div>
</div>

app/views/feedbacks/_form.html.erb
<%= form_for(feedback) do |f| %>
  <% if feedback.errors.any? %>
      <%= render 'shared/errors', object: feedback %>
  <% end %>

    <% opts = [positive: [name: 'Positive', id: 'positive'], negative:  [name: 'Negative', id: 'negative'], suggestion:  [name: 'Suggestion', id: 'suggestion']] %>
  <div class="field form-group">
    <%= f.label :status %>
    <%= select_tag "feedback[status]", "<option value='positive'>#{t'feedbacks.feedback.positive'}</option><option value='negative'>#{t'feedbacks.feedback.negative'}</option><option value='suggestion'>#{t'feedbacks.feedback.suggestion'}</option>".html_safe, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :feedback %>
    <%= md_simple_editor  do %>
      <%= f.text_area :feedback, class: 'form-control' %>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/feedbacks/_like_btn.html.erb
<% if feedback.liked_by?(current_user) %>
    <%= link_to feedback_unlike_path(feedback), method: :delete, remote: true, class: "btn btn-primary btn-flat" do %>
        <i class="fa fa-thumbs-o-up"></i> <%= feedback.likers_count %> Like
    <% end %>
<% else %>
    <%= link_to feedback_like_path(feedback), method: :post, remote: true, class: "btn btn-default btn-flat" do %>
        <i class="fa fa-thumbs-o-up"></i>  <%= feedback.likers_count if feedback.likers_count!=0 %> Like
    <% end %>
<% end %>

app/views/feedbacks/_timeline_item.html.erb
<div class="box box-widget">
  <div class="box-header with-border">
    <div class="user-block">
      <%= link_to profile_path(feedback.user.profile) do %>
          <%= show_profile_img(feedback.user, :medium) %>
      <% end %>
      <span class="username"><a href="#"><%= feedback.user.profile.firstname %> <%=feedback.user.profile.lastname %></a></span>
      <span class="description"><%= time_ago_in_words(feedback.created_at) %></span>
    </div>
    <!-- /.user-block -->
    <div class="box-tools">
      <% if can?(:crud, feedback) %>
      <!--<span class="pull-right">-->
        <%= link_to 'Show', feedback, class:'btn btn-xs btn-default' %>
        <%= link_to 'Edit', edit_feedback_path(feedback), class:'btn btn-xs btn-warning' %>
        <%= link_to 'Destroy', feedback, method: :delete, class:'btn btn-xs btn-danger', data: { confirm: 'Are you sure?' } %>
      <!--</span>-->
      <% end %>
      <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
      </button>
      <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
    </div>
    <!-- /.box-tools -->
  </div>
  <!-- /.box-header -->
  <div class="box-body">
    <!-- post text -->
    <p>
      <%= markdown(feedback.feedback) %>
    </p>
    <% if user_signed_in?  %>
      <%= render partial: 'feedbacks/like_btn', locals: { feedback: feedback } %>
    <% else %>
      <span class="pull-right text-muted"><%= feedback.likers_count %> likes </span>
    <% end %>
  </div>

  <%= render partial: 'comments/comments', locals: { commentable: feedback } %>

  <div class="overlay hidden">
    <i class="fa fa-refresh fa-spin"></i>
  </div>
</div>

app/views/feedbacks/edit.html.erb
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- okgo feedbacks -->
<ins class="adsbygoogle"
     style="display:block;margin-bottom:20px;"
     data-ad-client="ca-pub-5677662134676433"
     data-ad-slot="8674757998"
     data-ad-format="auto"></ins>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({});
</script>
<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title"><%= t('feedbacks.feedback.edit_feedback') %></h3>
  </div><!-- /.box-header -->
  <div class="box-body">
    <%= render 'form', feedback: @feedback %>
  </div>

  <div class="box-footer">
    <%= link_to 'Show', @feedback, class: 'btn btn-default'  %> |
    <%= link_to 'Back', feedbacks_path, class: 'btn btn-default' %>
  </div>
</div>

app/views/feedbacks/index.html.erb
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- okgo feedbacks -->
<ins class="adsbygoogle"
     style="display:block;margin-bottom:20px;"
     data-ad-client="ca-pub-5677662134676433"
     data-ad-slot="8674757998"
     data-ad-format="auto"></ins>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({});
</script>

<div class="box">
  <div class="box-header">
    <%= link_to t('feedbacks.feedback.leave_feedback'), new_feedback_path, class: 'btn btn-primary btn-sm pull-right' %>
  </div>

  <div class="box-body">
    <ul class="timeline">
      <li class="time-label">
        <span class="bg-red">
          <%= I18n.l Time.zone.now, format: ("%A, %b %d") %>
        </span>
      </li>
      <% @feedbacks.each do |feedback| %>
          <li>
            <%= feedback_status(feedback.status).html_safe %>
            <div class="timeline-item">
              <%= render partial: 'feedback', locals: {feedback: feedback} %>
            </div>
          </li>
      <% end %>
    </ul>
  </div>
</div>
<%= paginate @feedbacks, window: 2 %>

app/views/feedbacks/new.html.erb
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- okgo feedbacks -->
<ins class="adsbygoogle"
     style="display:block;margin-bottom:20px;"
     data-ad-client="ca-pub-5677662134676433"
     data-ad-slot="8674757998"
     data-ad-format="auto"></ins>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({});
</script>
<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title"><%= t('feedbacks.feedback.new_feedback') %></h3>
  </div>
  <div class="box-body">
    <%= render 'form', feedback: @feedback %>
  </div>
  <div class="box-footer">
    <%= link_to 'Back', feedbacks_path, class: 'btn btn-default pull-right' %>
  </div>
</div>

app/views/feedbacks/show.html.erb
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- okgo feedbacks -->
<ins class="adsbygoogle"
     style="display:block;margin-bottom:20px;"
     data-ad-client="ca-pub-5677662134676433"
     data-ad-slot="8674757998"
     data-ad-format="auto"></ins>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({});
</script>
<%= render partial: 'feedbacks/feedback', locals: {feedback: @feedback} %>