config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, skip: [:session, :password, :registration], controllers: { omniauth_callbacks: "omniauth_callbacks" }
  devise_scope :user do
    get   '/users/auth/failure'   => 'omniauth_callbacks#failure'
    post  '/finish_registration'  => 'omniauth_callbacks#finish_registration'
    get   '/finish_registration'  => 'events#index'
  end
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users, skip: [:registrations, :omniauth_callbacks]
    devise_scope :user do
      resource :registration,
               only: [:new, :create, :edit, :update],
               path: 'users',
               path_names: { new: 'sign_up' },
               controller: 'devise/registrations',
               as: :user_registration do
        get :cancel
      end
    end

    resources :feedbacks do
      post 'like', to: 'socializations#like'
      delete 'unlike', to: 'socializations#unlike'
      resources :comments, module: :feedbacks
    end

    match 'notifications' => 'activities#notifications', :via => :get
    match 'notifications_count' => 'activities#notifications_count', :via => :get

    resources :activities, only: [:index]
    resources :languages
    resources :profiles do
      patch 'save_photo', to: 'profiles#save_photo'
      patch 'save_cover_img', to: 'profiles#save_cover_img'
    end

    resources :events do
      member do
        post 'members', to: 'events#members'
      end
      post 'like', to: 'socializations#like'
      delete 'unlike', to: 'socializations#unlike'
      resources :comments, module: :events
    end
    resources :event_memberships do
      collection do
        get 'as_tutor'
        get 'as_member'
        get 'show_event_members/:event_id' => 'event_memberships#show_event_members', as: :show_members
        post 'update_rate/:event_id/:rate_id' => 'event_memberships#update_rate', as: :update_rate
      end

      member do
        post 'member_attended' => 'event_memberships#member_attended', as: :member_attended
        post 'member_not_attended' => 'event_memberships#member_not_attended', as: :member_not_attended
        post 'rate_member' => 'event_memberships#rate_member', as: :rate
      end
    end
    post 'event_memberships/join/:event_id' => 'event_memberships#join', as:   :join_event
    delete 'event_memberships/leave/:event_id' => 'event_memberships#leave', as: :leave_event
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'events#index'
  end
end

app/views/shared/main_sidebar_elements/_sidebar_form.html.erb
<form action="#" method="get" class="sidebar-form">
  <div class="input-group">
    <input type="text" name="q" class="form-control" placeholder='<%= t 'sidebar_navigation.search' %>'>
    <span class="input-group-btn">
          <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
          </button>
        </span>
  </div>
</form>

app/views/shared/main_sidebar_elements/_sidebar_menu.html.erb
<ul class="sidebar-menu">
  <li class="header"><%= t 'sidebar_navigation.navigation' %></li>
  <!-- Optionally, you can add icons to the links -->
  <li class="<%= active_link_to_class(events_path, :active => :inclusive) %>">
    <%= link_to events_path do %>
        <i class="fa fa-calendar"></i> <span><%= t 'sidebar_navigation.events' %></span>
    <% end %>
  </li>
  <% if user_signed_in? %>
    <li class="<%= active_link_to_class(profile_path(current_user.profile), :active => :inclusive) %>" >
      <%= link_to profile_path(current_user.profile) do %>
          <i class="fa fa-user-o"></i> <span><%= t 'sidebar_navigation.my_profile' %></span>
      <% end %>
    </li>
  <% end %>
  <li class="treeview">
    <a href="#"><i class="fa fa-calendar-check-o"></i> <span><%= t 'sidebar_navigation.event_memberships.index' %></span>
      <span class="pull-right-container">
        <i class="fa fa-angle-left pull-right"></i>
      </span>
    </a>
    <ul class="treeview-menu">
      <li>
        <%= link_to as_member_event_memberships_path do %>
            <i class="fa fa-calendar-check-o"></i> <span><%= t 'sidebar_navigation.event_memberships.as_member' %></span>
        <% end %>
      </li>
      <li>
        <%= link_to as_tutor_event_memberships_path do %>
            <i class="fa fa-calendar-check-o"></i> <span><%= t 'sidebar_navigation.event_memberships.as_tutor' %></span>
        <% end %>
      </li>
    </ul>
  </li>



  <li class="<%= active_link_to_class(activities_path, :active => :inclusive) %>" >
    <%= link_to activities_path do %>
        <i class="fa fa-hourglass-3"></i> <span><%= t 'sidebar_navigation.activities' %></span>
    <% end %>
  </li>

  <li class="<%= active_link_to_class(feedbacks_path, :active => :inclusive) %>">
    <%= link_to feedbacks_path do %>
        <i class="fa fa-heart-o text-red"></i> <span><%= t 'sidebar_navigation.feedbacks' %></span>
    <% end %>
  </li>

  <% if current_user && current_user.admin? %>
    <li class="<%= active_link_to_class(languages_path, :active => :inclusive) %>" >
      <%= link_to languages_path do %>
          <i class="fa fa-circle-o"></i> <span><%= t 'sidebar_navigation.languages' %></span>
      <% end %>
    </li>
    <li>
      <%= link_to rails_admin_path do %>
          <i class="fa fa-wrench"></i> <span>Admin Panel</span>
      <% end %>
    </li>
  <% end %>
<!--  <li class="treeview">
    <a href="#"><i class="fa fa-circle-o"></i> <span>Multilevel</span>
      <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
    </a>
    <ul class="treeview-menu">
      <li><a href="#">Link in level 2</a></li>
      <li><a href="#">Link in level 2</a></li>
    </ul>
  </li>-->
</ul>

app/views/shared/main_sidebar_elements/_user_panel.html.erb
<div class="user-panel">
  <div class="pull-left image">
    <% if current_user.profile.photo? %>
        <%= image_tag(current_user.profile.photo.url('small'), class: "img-circle", alt: 'User Image') %>
    <% else %>
        <%= image_tag('small_missing.png', class: "img-circle", alt: 'User Image') %>
    <% end %>
  </div>
  <div class="pull-left info">
    <% if user_signed_in? %>
        <% if !current_user.profile.firstname.blank? %>
          <p><%= current_user.profile.firstname %></p>
        <% else %>
          <p><%= current_user.email %></p>
        <% end %>
    <% else %>
        <p>Hello</p>
    <% end %>
    <!-- Status -->
    <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
  </div>
</div>